# Generated by Django 2.2.3 on 2020-12-10 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion_Menu',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Personalizaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Opcion', models.CharField(max_length=2)),
                ('Plato_Fondo', models.CharField(max_length=100)),
                ('Ensalada', models.CharField(max_length=100)),
                ('Postre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Opcion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('ID_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Eleccion_Menu')),
            ],
        ),
    ]
