# Generated by Django 2.2.3 on 2020-12-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Fecha',
            field=models.DateField(help_text='Ingrese la Fecha del Menú (AAAA-MM-DD)'),
        ),
    ]
