# Generated by Django 2.2.3 on 2020-12-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_eleccion_menu_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleccion_Menu',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
