# Generated by Django 2.2.3 on 2020-12-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20201213_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Slack', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eleccion_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opcion', models.CharField(help_text='Ingrese la opción del menú que desee', max_length=100)),
                ('Personalizaciones', models.CharField(help_text='Especifique las personalizaciones del menú si es necesario', max_length=300, null=True)),
                ('Fecha', models.DateField()),
                ('Eleccion_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Empleado')),
            ],
        ),
    ]
